name: brendanlandis.com
services:
    - environment_slug: php
      github:
          branch: main
          deploy_on_push: true
          repo: brendanlandis/brendanlandis.com
      name: brendanlandis.com
